### ISSUE TITLE
Automate surge alerts on landing page

### ISSUE THREAD

**Issue by guipizzini** [IFRCGo/ifrcgo_v2#17]

**Comment by dalekunce** [comment]
Is there an API for this. Do we need to build something that listens for an email?

**Comment by guipizzini** [comment]
For now we have an HXL proxy pulling data from a google spreadsheet but we have all Alerts going into a standard email box and would be great to just import the content from the emails rather than me updating the google spreadsheet.

**Comment by guipizzini** [comment]
@Zibethin the HXL proxy is not functioning anymore in automating the alerts from the google sheet.

**Comment by SimonbJohnson** [comment]
It's pulling through the first 5, not the last 5.

**Comment by Zibethin** [comment]
fixed in this pull request https://github.com/IFRCGo/homepage/pull/3 (also not sure I understand what all the different repositories do, should I add the alert box in this repo too?)

**Comment by guipizzini** [comment]
@Zibethin the alerts are correctly showing up now on the http://ifrcgo.org/homepage/ page and repo but we need to migrate the alerts to this page and repo: http://ifrcgo.org/ifrcgo_v2/

**Comment by guipizzini** [comment]
@Zibethin alerts are still not appearing on http://ifrcgo.org/ifrcgo_v2/

anything wrong?

**Comment by Zibethin** [comment]
It's sitting with Dale's commits on the development branch at the moment
